### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by yangfan-coder** [g-plane/tiny-package-manager#3]
I tried using an empty project initialization, such as: `npx create-react-app my-app` ，Then I downloaded the project clone and directly ran `yarn build` locally,，Conducted `npm link ` ，Deleted the project's `node_modules`,Install using `tiny-pm` and report an error directly 

![image](https://github.com/g-plane/tiny-package-manager/assets/14069048/6220dfcd-283c-4c06-bc0d-d5623666f6b8)

**Comment by yangfan-coder** [comment]
Development environment: MAC
Node version: v16.19.0

**Comment by g-plane** [comment]
I guess it's a network error. The `electron-to-chromium` can be installed successfully when a project has the only one `electron-to-chromium` dependency.

**Comment by g-plane** [comment]
I switched to another HTTP request library. It may not help, but you can try again.

**Comment by yangfan-coder** [comment]
In fact, I have repeatedly tried several times locally, and each time the download of a different installation package failed. I can see from the error that it is a network problem, but my question is: I use the same method and the same registry, but NPM or YARN are not any problems? This makes me very distressed! I don't know exactly where the problem occurred

**Comment by g-plane** [comment]
I guess one possible reason is that many packages are downloaded at the same time. However, this project is just for learning and demonstration. It won't deeply solve edge cases.

**Comment by yangfan-coder** [comment]
I think it should also be that there are packages in dependencies, but it's okay. The overall process can be streamlined, and I have learned a lot from it. Thank you very much
