### ISSUE TITLE
list.ts explanation

### ISSUE THREAD

**Issue by oliknight1** [g-plane/tiny-package-manager#5]
I was wondering if you could provide a little more information on the list file and it's role in the application, i'm attempting to do something similar using Rust.

Thanks for putting together the repo it's been great for learning 😄

**Comment by g-plane** [comment]
Mainly it's collecting dependencies. Code is written several years ago so I'm not sure if I remember correctly. You can look at the entrance function and trace how it goes: https://github.com/g-plane/tiny-package-manager/blob/643fe89cf76e497a03fa1124c6e5748275a1a698/src/list.ts#L192
